### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NightRaidGamer** [Idov31/Nidhogg#31]
i compiled the driver and tested it on windows 7 pro x64 and windows 11 enterprise x64 and when i start the driver i got a blue screen with the error "SYSTEM THREAD EXCEPTION NOT HANDLED" both machines were with the test mode activated so I can load the driver, do you know how I solve this error?

**Comment by Idov31** [comment]
When you are opening an issue, use the format.
Regardless, please read the readme - only windows 10 versions and windows 11 versions x64 are supported and NOT Windows 7.

With the given information I cannot help so fill up the missing fields:

- Exact windows version and build
- Nidhogg's version

**Comment by Idov31** [comment]
Thanks for trying out Nidhogg!
This issue is fixed now and the fix is available on the main branch.

**Comment by NightRaidGamer** [comment]
@Idov31 could you add support for windows 7 in the future?

**Comment by Idov31** [comment]
@NightRaidGamer , please see #33 .
