### ISSUE TITLE
[BUG] File protection in Microsoft Windows Server 2016 Datacenter, blue screen of death occurs

### ISSUE THREAD

**Issue by crab2019** [Idov31/Nidhogg#45]
File protection in Microsoft Windows Server 2016 Datacenter, blue screen of death occurs
NidhoggClient.exe file add c:\test\test.txt Soon after the command is executed, the system displays a blue screen

**Comment by Idov31** [comment]
Hey,
- Did you try the `dev` branch as well?
- What was the BSOD error code? If it wasn't [0x109 (Critical Structure Corruption)](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x109---critical-structure-corruption) please look at #44 . If it was 0x109, please look the [README](https://github.com/Idov31/Nidhogg?tab=readme-ov-file#patchguard-triggering-features), this is a known behavior.

**Comment by crab2019** [comment]
dev branch tests do not have a blue screen. Only the release was tested yesterday
Release termination code :BAD POOL HEADER

**Comment by crab2019** [comment]
Repeat file add and file clear several times
After running for a while.
You will still get a blue screen and the error code will still be :BAD POOL HEADER

**Comment by Idov31** [comment]
I'm glad to hear that the dev branch works. I will merge the dev branch soon after I fix a few more things.
