### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PROMPTYLOL** [Idov31/Nidhogg#49]
Cannot open include file: 'ntifs.h': No such file or directory
discarding return value of function with [[nodiscard]] attribute
discarding return value of function with [[nodiscard]] attribute
'=': conversion from 'wchar_t' to 'char', possible loss of data

**Comment by Idov31** [comment]
I'm closing this issue. Please reopen this issue with meaningful issue name in the template and append the file names for these warnings and errors.
